
<?php

/**
 * @file
 * Facebook Conversion
 */
 ?>
<!-- Facebook Conversion Code for DS 14130 Murakami Iyer FB -->
<script>
(function() {
var _fbq = window._fbq || (window._fbq = []);
if (!_fbq.loaded) {
var fbds = document.createElement('script');
fbds.async = true;
fbds.src = '//connect.facebook.net/en_US/fbds.js';
var s = document.getElementsByTagName('script')[0];
s.parentNode.insertBefore(fbds, s);
_fbq.loaded = true;
}
})();
window._fbq = window._fbq || [];
window._fbq.push(['track', '6012264314829', {'value':'0.01','currency':'USD'}]);
</script>
<noscript>
<img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/tr?ev=6012264314829&cd[value]=0.01&cd[currency]=USD&noscript=1" />
</noscript>