<?php

/**
 * @file
 * Google Addwords
 */
 ?>
 
<!--Lukens Google Adwords Remarketing -->
<div style="display:none"><!--for mobile -->
<script type="text/javascript">
	/* <![CDATA[ */
	var google_conversion_id = 969779172;
	var google_custom_params = window.google_tag_params;
	var google_remarketing_only = true;
	var google_conversion_format = 3;
	/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js"></script>
<noscript>
	<div style="display:inline;">
		<img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/969779172/?value=0&amp;guid=ON&amp;script=0"/>
	</div>
</noscript>
<!--Broad Google Adwords Remarketing -->
<script type="text/javascript">
	/* <![CDATA[ */
	var google_conversion_id = 970103636;
	var google_custom_params = window.google_tag_params;
	var google_remarketing_only = true;
	var google_conversion_format = 3;
	/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js"></script>
<noscript>
	<div style="display:inline;">
		<img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/970103636/?value=0&amp;guid=ON&amp;script=0"/>
	</div>
</noscript>
</div><!-- end: for mobile -->