<?php

/**
 * @file
 * mailchimp Form and inline js
 */
 ?>
<div id="mc_embed_signup">
	<form action="http://thebroad.us7.list-manage1.com/subscribe/post?u=396d50be7573eef8a00e0843f&amp;id=e65543aba2" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>

		<div id="mc_embed_logo">
			<img src="/sites/default/files/images/popupLogo.png" />
		</div>
		<div id="mc_embed_text">
			<p>
				Get construction updates, information about upcoming programs, and more.
			</p>
			<p>
				Sign-up for The Broad's email list.
			</p>
		</div>
		<div class="clear"></div>
		<div class="indicates-required">
			<span class="asterisk">*</span> Required Fields
		</div>

		<div class="mc-field-group">
			<label for="mce-FNAME" class="italic"> First Name: </label>
			<input type="text" value="" name="FNAME" id="mce-FNAME">
		</div>
		<div class="mc-field-group">
			<label for="mce-LNAME" class="italic"> Last Name:  </label>
			<input type="text" value="" name="LNAME" id="mce-LNAME">
		</div>

		<div class="mc-field-group">
			<label for="mce-EMAIL" class="italic"> Email Address: <span class="asterisk">* </span> </label>
			<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
		</div>

		<a href="#" id="mc_embed_close" class="mc_embed_close">Close</a>
		<input type="hidden" name="src_code" value="BRODS14114LBX01">
		<div id="mce-responses" class="clear">
			<div class="response" id="mce-error-response" style="display:none"></div>
			<div class="response" id="mce-success-response" style="display:none"></div>
		</div>
		<!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->

		<div style="position: absolute; left: -5000px;">
			<input type="text" name="b_396d50be7573eef8a00e0843f_e65543aba2" value="">
		</div>
		<div class="clear"></div>

		<!-- to add a hidden field for source of signup -->
		<input type="hidden" name="SIGNUP" id="SIGNUP" value="web popup" />

		<div>
			<input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe">
		</div>
	</form>
</div>
<script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script>
<script type='text/javascript'>
(function($) {
window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';fnames[3]='MMERGE3';ftypes[3]='address';fnames[4]='MMERGE4';ftypes[4]='birthday';fnames[10]='MMERGE10';ftypes[10]='text';fnames[11]='MMERGE11';ftypes[11]='text';fnames[12]='MMERGE12';ftypes[12]='phone';fnames[5]='MMERGE5';ftypes[5]='text';fnames[6]='SIGNUP';ftypes[6]='text';
window.mc.showPopup = true;window.mc.delayPopup = 5000;if (mc.showPopup) mc.evalPopup();
/*
$('#mc-embedded-subscribe-form').submit(function (e) {

    //hide popup 
    $("#mc_embed_signup").hide();
}); */
function checkSuccess() {
     if ($('#mce-success-response').is(':visible')) {
        $('#mc_embed_signup').hide();
    }
} 
window.setInterval(checkSuccess, 4000);

}(jQuery));
var $mcj = jQuery.noConflict(true);


</script>