
<?php

/**
 * @file
 * Popup Promo DOM
 * see thebroa/template.php 
 * function thebroad_preprocess_page(&$vars) {}
 * @line 57
 * above is a function that load the JS in the <head section>
 */
 ?>

<!--<div id="promo-wrapper" style='display:none'>
<div id="promo-popup">
<center>
<a href="http://www.blouinartinfo.com/broadlivestreamseries" target="_blank"><img src="/sites/default/files/images/Murakami-Iyer-popup.jpg" /></a>
</center>
</div>-->
<!--<div style="margin:0 auto; display:block; width:800px; background:white; text-align:right;">
No thanks, take me to the site
</div>-->