<?php
/**
 * Implementation of hook_entity_info_alter().
 *
 * Redirect any links to program taxonomy terms to their corresponding node page.
 */
 
function tags_term_entity_info_alter(&$entity_info) {
	
  $entity_info['taxonomy_term']['uri callback'] = 'tags_term_taxonomy_term_uri';
 	
}

/**
 * Entity uri callback for taxonomy terms. 
 */
function tags_term_taxonomy_term_uri($term) {
   //$tags = str_replace(' ', '-', strtolower($term->name));
 
  if ( isset($term->name) && $term->vocabulary_machine_name =='tags') {
    
     return array(
      'path' => 'tags/' . str_replace(' ', '-', strtolower($term->name)),
    );
  }
  
  else {
    return array(
      'path' => 'taxonomy/term/' . $term->tid,
    );
  }
   
}
